### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by ryanfrancesconi** [orchetect/OTAtomics#2]
I'm putting this here until I have time to look at it, or if you would like to look at it.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2917795/156427873-b011e469-e5e9-47d3-bad6-fc33bfa6c125.png">

<img width="509" alt="image" src="https://user-images.githubusercontent.com/2917795/156428008-fb5b684d-394b-4398-a571-6d0e7a9a2fc1.png">

```
<OTAtomicsThreadSafe<Optional<String>>: 0x600003d17e30>
```

**Comment by orchetect** [comment]
Retain isn't in OTAtomics, it's in OTOperations
